--#####--###########################################################################
--###########################################################################
-- SCRIPT DE MIGRACION Y CREACION DE OBJETOS NECESARIOS
-- GRUPO: DAVID_Y_LOS_COCODRILOS
--###########################################################################
--###########################################################################

USE [GD1C2017]
GO

--###########################################################################
--###########################################################################
---------------------VERIFICACION EXISTENCIA DE OBJETOS----------------------
--###########################################################################
--###########################################################################

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ITEM_FACTURA') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.ITEM_FACTURA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ITEM_RENDICION') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.ITEM_RENDICION

--TABLAS
IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.VIAJE') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.VIAJE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.TURNO_AUTOMOVIL') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.TURNO_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.VIAJE_INCONSISTENCIAS') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.VIAJE_INCONSISTENCIAS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.FACTURA') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.FACTURA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.RENDICION') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.RENDICION

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AUTOMOVIL') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.AUTOMOVIL


IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS_CLIENTE') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS_CLIENTE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS_CHOFER') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS_CHOFER

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS_ADMINISTRADOR') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS_ADMINISTRADOR


IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.CLIENTE') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.CLIENTE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.CHOFER') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.CHOFER

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ADMINISTRADOR') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.ADMINISTRADOR

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ROL_USUARIO') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.ROL_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.USUARIO') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ROL') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.TURNO') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.TURNO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MODELO') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.MODELO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MARCA') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.MARCA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MODELO') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.MODELO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MARCA') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.MARCA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.PERIODO') IS NOT NULL
DROP TABLE DAVID_Y_LOS_COCODRILOS.PERIODO


--PROCEDURES
IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MODIFICAR_NOMBRE_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_NOMBRE_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_MODELO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_MODELO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_VIAJE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_VIAJE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.RENDIR') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.RENDIR

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.FACTURAR') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.FACTURAR

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_MARCA') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_MARCA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CLIENTE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CLIENTE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CHOFER') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CHOFER

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_TURNO_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_TURNO_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_TURNO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_TURNO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE_INCONSISTENCIAS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE_INCONSISTENCIAS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.UPDATE_RENDICION') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.UPDATE_RENDICION

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_RENDICION') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_RENDICION

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_RENDICION') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_RENDICION

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.UPDATE_FACTURA') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.UPDATE_FACTURA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_FACTURA') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_FACTURA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_FACTURA') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_FACTURA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_MODELO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_MODELO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_MARCA') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_MARCA

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.CARGA_DATOS_INICIALES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.CARGA_DATOS_INICIALES

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CLIENTE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CLIENTE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CHOFER') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CHOFER

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_CLIENTE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_CLIENTE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_CHOFER') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_CHOFER

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MIGRACION_PERIODO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_PERIODO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.INGRESAR_USUARIO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.INGRESAR_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_FUNCIONALIDAD_A_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_FUNCIONALIDAD_A_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.REMOVER_FUNCIONALIDAD_A_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.REMOVER_FUNCIONALIDAD_A_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.INHABILITAR_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.HABILITAR_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.HABILITAR_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MODIFICAR_NOMBRE_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_NOMBRE_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ALTA_CLIENTE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.ALTA_CLIENTE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.INHABILITAR_USUARIO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MODIFICAR_USUARIO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ALTA_USUARIO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.ALTA_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.BUSCAR_USUARIO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.BUSCAR_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_VIAJE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_VIAJE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_VIAJE') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_VIAJE

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FACTURAS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FACTURAS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_RENDICIONES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_RENDICIONES

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.RENDIR') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.RENDIR

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.FACTURAR') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.FACTURAR

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONES_PARA_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONES_PARA_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ALTA_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.ALTA_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_MARCAS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_MARCAS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_MODELOS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_MODELOS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_TURNOS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TURNOS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.AGREGAR_TURNO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_TURNO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MODIFICAR_TURNO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_TURNO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.INHABILITAR_TURNO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_TURNO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_TURNOS_HABILITADOS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TURNOS_HABILITADOS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVILES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVILES


IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVILES_HABILITADOS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVILES_HABILITADOS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.INHABILITAR_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.MODIFICAR_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_PARA_USUARIO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_PARA_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_PARA_USUARIO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_PARA_USUARIO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ESTADISTICA_RECAUDACION') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_RECAUDACION

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ESTADISTICA_VIAJES_MAS_LARGOS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_VIAJES_MAS_LARGOS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ESTADISTICA_CLIENTES_CONSUMO') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_CLIENTES_CONSUMO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.ESTADISTICA_CLIENTE_AUTOMOVIL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_CLIENTE_AUTOMOVIL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.BUSCAR_TODOS_LOS_ROLES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.BUSCAR_TODOS_LOS_ROLES

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.BUSCAR_ROLES_HABILITADOS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.BUSCAR_ROLES_HABILITADOS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.BUSCAR_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.BUSCAR_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONES_HABILITADAS_PARA_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONES_HABILITADAS_PARA_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_TODAS_LAS_FUNCIONES_PARA_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TODAS_LAS_FUNCIONES_PARA_ROL

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_HABILITADOS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_HABILITADOS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES_HABILITADAS') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES_HABILITADAS

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_TODAS_LAS_FUNCIONALIDADES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TODAS_LAS_FUNCIONALIDADES

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_TODOS_LOS_ROLES') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TODOS_LOS_ROLES

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES_NO_ASIGNADAS_A_ROL') IS NOT NULL
DROP PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES_NO_ASIGNADAS_A_ROL
 
IF TYPE_ID('DAVID_Y_LOS_COCODRILOS.T_TURNOS') IS NOT NULL
DROP TYPE DAVID_Y_LOS_COCODRILOS.T_TURNOS


--FUNCTIONS
IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.fGetTurno') IS NOT NULL
DROP FUNCTION DAVID_Y_LOS_COCODRILOS.fGetTurno

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.fGenRandomViajeID') IS NOT NULL
DROP FUNCTION DAVID_Y_LOS_COCODRILOS.fGenRandomViajeID

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_INICIO_PERIODO') IS NOT NULL
DROP FUNCTION DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_INICIO_PERIODO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_FIN_PERIODO') IS NOT NULL
DROP FUNCTION DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_FIN_PERIODO

IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.CANT_INTENTOS_LOGIN_FALLIDOS') IS NOT NULL
DROP FUNCTION DAVID_Y_LOS_COCODRILOS.CANT_INTENTOS_LOGIN_FALLIDOS




--TRIGGERS
IF OBJECT_ID('DAVID_Y_LOS_COCODRILOS.tVerificarTurno') IS NOT NULL
DROP TRIGGER DAVID_Y_LOS_COCODRILOS.tVerificarTurno

GO


--SCHEMA
IF EXISTS (	SELECT  *
            FROM sys.schemas
            WHERE name = 'DAVID_Y_LOS_COCODRILOS' ) 
EXEC('DROP SCHEMA [DAVID_Y_LOS_COCODRILOS]');


IF NOT EXISTS ( SELECT  *
                FROM    sys.schemas
                WHERE   name = 'DAVID_Y_LOS_COCODRILOS' ) 
EXEC('CREATE SCHEMA [DAVID_Y_LOS_COCODRILOS] AUTHORIZATION [gd]');
 

GO



--###########################################################################
--###########################################################################
----------------------------CREACION DE TABLAS--------------------------------
--###########################################################################
--###########################################################################

--------------------------------------
-------------TABLA PERIODO------------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.PERIODO (
	PERIODO_ANIO  	int,
	PERIODO_MES 	int,
	PERIODO_INICIO  datetime,
	PERIODO_FIN datetime,
	PERIODO_CLIENTE numeric(18,0),
	primary key (PERIODO_ANIO, PERIODO_MES, PERIODO_CLIENTE)
);

--------------------------------------
-------------TABLA ROL----------------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.ROL (
	ROL_ID  		int IDENTITY(1,1),
	ROL_DETALLE 	varchar(255) UNIQUE,
	ROL_HABILITADO  integer DEFAULT 1,
	primary key (ROL_ID)
);

--------------------------------------
----------TABLA FUNCIONALIDAD---------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD (
	FUNCIONALIDAD_ID 			int identity(1,1),
	FUNCIONALIDAD_DETALLE		varchar(255),
	FUNCIONALIDAD_HABILITADO	integer DEFAULT 1,
	primary key (FUNCIONALIDAD_ID)
);


------------------------------------------------------
---------------TABLA FUNCIONALIDAD_ROL----------------
------------------------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL (
	ROLFUN_FUNCIONALIDAD		int,
	ROLFUN_ROL					int,
	foreign key (ROLFUN_FUNCIONALIDAD) 	references DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD,
	foreign key (ROLFUN_ROL) 			references DAVID_Y_LOS_COCODRILOS.ROL,
	primary key (ROLFUN_FUNCIONALIDAD, ROLFUN_ROL)
);


--------------------------------------
-------------TABLA USUARIO------------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.USUARIO (
	USUARIO_NOMBRE		varchar(255),
	USUARIO_APELLIDO	varchar(255),
	USUARIO_DNI			numeric(18,0),
	USUARIO_MAIL		varchar(50),
	USUARIO_TEL			char(18),
	USUARIO_DIR			varchar(255),
	USUARIO_PISO		int,
	USUARIO_DPTO		char(10) DEFAULT '-',
	USUARIO_LOCALIDAD	varchar(50),
	USUARIO_CODPOS		varchar(10),
	USUARIO_FNAC		datetime,
	USUARIO_USERNAME	char(35),
	USUARIO_PASSWORD	char(100),
	USUARIO_INTENTOS_LOGIN	int DEFAULT 0,
	USUARIO_HABILITADO	int DEFAULT 1
	primary key (USUARIO_DNI)
);


--------------------------------------
-------------TABLA CLIENTE------------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.CLIENTE (
	CLIENTE_ID	numeric(18,0) PRIMARY KEY,
	CLIENTE_HABILITADO	int DEFAULT 1
	foreign key (CLIENTE_ID) references DAVID_Y_LOS_COCODRILOS.USUARIO
)


--------------------------------------
-------------TABLA CHOFER-------------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.CHOFER (
	CHOFER_ID	numeric(18,0) PRIMARY KEY,
	CHOFER_HABILITADO	int DEFAULT 1
	foreign key (CHOFER_ID) references DAVID_Y_LOS_COCODRILOS.USUARIO
)


--------------------------------------
---------TABLA ADMINISTRADOR----------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.ADMINISTRADOR (
	ADMIN_ID	numeric(18,0) PRIMARY KEY,
	ADMIN_HABILITADO	int DEFAULT 1
	foreign key (ADMIN_ID) references DAVID_Y_LOS_COCODRILOS.USUARIO
)


--------------------------------------
-------------TABLA ROL_USUARIO--------
--------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.ROL_USUARIO (
	USROL_USUARIO			numeric(18,0),
	USROL_ROL				int,
	USROL_HABILITADO		bit DEFAULT 1
	foreign key (USROL_USUARIO) 		references DAVID_Y_LOS_COCODRILOS.USUARIO,
	foreign key (USROL_ROL) 			references DAVID_Y_LOS_COCODRILOS.ROL,
	primary key (USROL_USUARIO, USROL_ROL)
);


----------------------------------------
-------------TABLA MARCA----------------
----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.MARCA (
	MARCA_ID Int IDENTITY(1,1),
	MARCA_DETALLE varchar(255),
	primary key (MARCA_ID)
)

----------------------------------------
-------------TABLA MODELO---------------
----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.MODELO (
	MODELO_ID Int IDENTITY(1,1),
	MODELO_MARCA Int ,
	MODELO_DETALLE varchar(255),
	primary key (MODELO_ID, MODELO_MARCA),
	foreign key (MODELO_MARCA) references DAVID_Y_LOS_COCODRILOS.MARCA
);


----------------------------------------
-------------TABLA TURNO----------------
----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.TURNO (
	TURNO_ID INT IDENTITY(1,1),
	TURNO_HORA_INICIO numeric(18,0),
	TURNO_HORA_FIN numeric(18,0),
	TURNO_DESCRIPCION varchar(255),
	TURNO_VALOR_KILOMETRO numeric(18,2),
	TURNO_PRECIO_BASE numeric(18,2),
	TURNO_HABILITADO bit,
	primary key (TURNO_ID)
);


-----------------------------------------
-------------TABLA AUTOMOVIL-------------
-----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.AUTOMOVIL (
	AUTOMOVIL_PATENTE varchar(10),
	AUTOMOVIL_MARCA Int,
	AUTOMOVIL_MODELO Int,
	AUTOMOVIL_TURNO INT,
	AUTOMOVIL_CHOFER numeric(18,0),
	AUTOMOVIL_HABILITADO bit,
	primary key (AUTOMOVIL_PATENTE, AUTOMOVIL_TURNO),
	foreign key (AUTOMOVIL_CHOFER) references DAVID_Y_LOS_COCODRILOS.CHOFER,
	foreign key (AUTOMOVIL_MARCA) references DAVID_Y_LOS_COCODRILOS.MARCA,
	foreign key (AUTOMOVIL_MODELO, AUTOMOVIL_MARCA) references DAVID_Y_LOS_COCODRILOS.MODELO,
	foreign key (AUTOMOVIL_TURNO) REFERENCES DAVID_Y_LOS_COCODRILOS.TURNO
);

CREATE TABLE DAVID_Y_LOS_COCODRILOS.TURNO_AUTOMOVIL(
	TA_AUTOMOVIL	VARCHAR(20),
	TA_TURNO		INT,
	TA_HABILITADO	BIT,

	primary key (TA_AUTOMOVIL, TA_TURNO),	
)

----------------------------------------
-------------TABLA VIAJE----------------
----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.VIAJE (
	VIAJE_ID Int IDENTITY(1,1),
	VIAJE_CHOFER numeric(18,0),
	VIAJE_CLIENTE numeric(18,0),
	VIAJE_AUTOMOVIL_PATENTE varchar(10),
	VIAJE_TURNO INT,
	VIAJE_CANTIDAD_KM numeric(18,0),
	VIAJE_FECHA_INICIO datetime,
	VIAJE_FECHA_FIN datetime,
	primary key (VIAJE_CHOFER, VIAJE_FECHA_INICIO, VIAJE_CLIENTE),
	foreign key (VIAJE_CHOFER) references DAVID_Y_LOS_COCODRILOS.CHOFER,
	foreign key (VIAJE_CLIENTE) references DAVID_Y_LOS_COCODRILOS.CLIENTE,
	foreign key (VIAJE_AUTOMOVIL_PATENTE, VIAJE_TURNO) references DAVID_Y_LOS_COCODRILOS.AUTOMOVIL,
	foreign key (VIAJE_TURNO) references DAVID_Y_LOS_COCODRILOS.TURNO
);

----------------------------------------
-------------TABLA VIAJE INCONSISTENCIAS----------------
----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.VIAJE_INCONSISTENCIAS (
	VIAJE_ID Int IDENTITY(1,1),
	VIAJE_CHOFER numeric(18,0),
	VIAJE_CLIENTE numeric(18,0),
	VIAJE_AUTOMOVIL_PATENTE varchar(10),
	VIAJE_TURNO INT,
	VIAJE_CANTIDAD_KM numeric(18,0),
	VIAJE_FECHA_INICIO datetime,
	VIAJE_FECHA_FIN datetime,
	primary key (VIAJE_CHOFER, VIAJE_FECHA_INICIO, VIAJE_CLIENTE),
	foreign key (VIAJE_CHOFER) references DAVID_Y_LOS_COCODRILOS.CHOFER,
	foreign key (VIAJE_CLIENTE) references DAVID_Y_LOS_COCODRILOS.CLIENTE,
	foreign key (VIAJE_AUTOMOVIL_PATENTE, VIAJE_TURNO) references DAVID_Y_LOS_COCODRILOS.AUTOMOVIL,
	foreign key (VIAJE_TURNO) references DAVID_Y_LOS_COCODRILOS.TURNO
);


----------------------------------------
-------------TABLA RENDICION------------
----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.RENDICION (
	RENDICION_ID int IDENTITY(1,1),
	RENDICION_FECHA datetime,
	RENDICION_CHOFER numeric(18,0),
	RENDICION_TURNO INT,
	RENDICION_IMPORTE numeric(18,2),
	primary key (RENDICION_CHOFER, RENDICION_FECHA, RENDICION_TURNO),
	foreign key (RENDICION_TURNO) references DAVID_Y_LOS_COCODRILOS.TURNO,
	foreign key (RENDICION_CHOFER) references  DAVID_Y_LOS_COCODRILOS.CHOFER
);


----------------------------------------
----------TABLA ITEM RENDICION----------
----------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.ITEM_RENDICION (
	ITEMR_IMPORTE numeric(18,2),
	ITEMR_CHOFER numeric(18,0),
	ITEMR_CLIENTE numeric(18,0),
	ITEMR_FECHA datetime,
	ITEMR_TURNO INT,
	ITEMR_FECHA_VIAJE datetime,
	primary key(ITEMR_CHOFER, ITEMR_CLIENTE, ITEMR_FECHA, ITEMR_TURNO, ITEMR_FECHA_VIAJE),
	foreign key (ITEMR_CHOFER, ITEMR_FECHA, ITEMR_TURNO) references DAVID_Y_LOS_COCODRILOS.RENDICION,
	foreign key (ITEMR_CHOFER, ITEMR_FECHA_VIAJE, ITEMR_CLIENTE) references DAVID_Y_LOS_COCODRILOS.VIAJE,
);


---------------------------------------
-------------TABLA FACTURA-------------
---------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.FACTURA (
	FACTURA_CLIENTE numeric(18,0),
	FACTURA_ID int IDENTITY(1,1),
	FACTURA_ANIO int,
	FACTURA_PERIODO int,
	FACTURA_IMPORTE numeric(18,2)
	primary key (FACTURA_CLIENTE, FACTURA_ANIO, FACTURA_PERIODO),
	foreign key (FACTURA_CLIENTE) references DAVID_Y_LOS_COCODRILOS.CLIENTE
);


-----------------------------------------------------
----------------TABLA ITEM FACTURA-------------------
-----------------------------------------------------
CREATE TABLE DAVID_Y_LOS_COCODRILOS.ITEM_FACTURA (
	ITEMF_CHOFER numeric(18,0),
	ITEMF_FECHA_VIAJE datetime,
	ITEMF_CLIENTE numeric(18,0),
	ITEMF_ANIO int,
	ITEMF_PERIODO int,
	ITEMF_IMPORTE numeric(18,2)
	primary key (ITEMF_CHOFER, ITEMF_FECHA_VIAJE, ITEMF_CLIENTE, ITEMF_ANIO, ITEMF_PERIODO),
	foreign key (ITEMF_CLIENTE, ITEMF_ANIO, ITEMF_PERIODO) references DAVID_Y_LOS_COCODRILOS.FACTURA,
	foreign key (ITEMF_CHOFER, ITEMF_FECHA_VIAJE, ITEMF_CLIENTE) references DAVID_Y_LOS_COCODRILOS.VIAJE
);



GO

--###########################################################################
--###########################################################################
----------------------------CREACION DE FUNCIONES----------------------------
--###########################################################################
--###########################################################################
	CREATE FUNCTION DAVID_Y_LOS_COCODRILOS.fGetTurno
	(@HORA_INICIO DATETIME, @HORA_FIN DATETIME)
	RETURNS INT
	AS
	BEGIN
		RETURN (SELECT TURNO_ID FROM DAVID_Y_LOS_COCODRILOS.TURNO WHERE TURNO_HORA_INICIO = @HORA_INICIO AND TURNO_HORA_FIN = @HORA_FIN)
	END
	GO



--###########################################################################
--###########################################################################
----------------------------MIGRACIONES DE DATOS-----------------------------
--###########################################################################
--###########################################################################


-----------------------------------------------------
--------------CARGA DATOS INICIALES------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.CARGA_DATOS_INICIALES
AS
BEGIN


	------------------------------------
	------------CARGA ROLES-------------
	------------------------------------
	INSERT	INTO DAVID_Y_LOS_COCODRILOS.ROL(ROL_DETALLE) 
			VALUES ('admin');
	INSERT	INTO DAVID_Y_LOS_COCODRILOS.ROL(ROL_DETALLE) 
			VALUES ('cliente');
	INSERT	INTO DAVID_Y_LOS_COCODRILOS.ROL(ROL_DETALLE) 
			VALUES ('chofer');
			

	------------------------------------
	--------CARGA USUARIO ADMIN --------
	------------------------------------
	INSERT	INTO DAVID_Y_LOS_COCODRILOS.USUARIO (USUARIO_DNI, USUARIO_USERNAME, USUARIO_PASSWORD)
			VALUES(0, 'admin', 'e6b87050bfcb8143fcb8db0170a4dc9ed00d904ddd3e2a4ad1b1e8dc0fdc9be7');
	INSERT INTO DAVID_Y_LOS_COCODRILOS.ADMINISTRADOR(ADMIN_ID)
			VALUES(0);
	INSERT INTO DAVID_Y_LOS_COCODRILOS.ROL_USUARIO (USROL_USUARIO, USROL_ROL)
			VALUES(0, 1);


	------------------------------------
	--------CARGA FUNCIONALIDADES-------
	------------------------------------
	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'ABM Automóviles',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'ABM Turnos',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'ABM Roles',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'Alta Administradores',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'ABM Choferes',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'ABM Clientes',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'Registro de Viajes',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'Rendición de Viajes',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'Facturación',
		1
	);

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD(
	FUNCIONALIDAD_DETALLE,
	FUNCIONALIDAD_HABILITADO)
	VALUES (
		'Estadísticas',
		1
	);


	------------------------------------------
	--------CARGA FUNCIONALIDADES ADMIN-------
	------------------------------------------
	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL(
	ROLFUN_FUNCIONALIDAD,
	ROLFUN_ROL
	) VALUES (1, 1), 
			 (2, 1), 
			 (3, 1), 
			 (4, 1), 
			 (5, 1),
			 (6, 1),
			 (7, 1),
			 (8, 1),
			 (9, 1),
			 (10, 1);


	------------------------------------------
	------CARGA FUNCIONALIDADES CLIENTE-------
	------------------------------------------
	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL(
	ROLFUN_FUNCIONALIDAD,
	ROLFUN_ROL
	) VALUES (1, 2), 
			 (2, 2), 
			 (3, 2);


	------------------------------------------
	-------CARGA FUNCIONALIDADES CHOFER-------
	------------------------------------------
	INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL(
	ROLFUN_FUNCIONALIDAD,
	ROLFUN_ROL
	) VALUES (1, 3), 
			 (2, 3);



END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.CARGA_DATOS_INICIALES')
GO




-----------------------------------------------------
----------------MIGRACION USUARIO--------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CLIENTE
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.USUARIO (
		USUARIO_DNI,
		USUARIO_TEL,
		USUARIO_NOMBRE,
		USUARIO_APELLIDO,
		USUARIO_MAIL,
		USUARIO_DIR,
		USUARIO_FNAC,
		USUARIO_USERNAME,
		USUARIO_PASSWORD
	)	SELECT	distinct(m.Cliente_Dni),
				m.Cliente_Telefono,
				m.Cliente_Nombre,
				m.Cliente_Apellido,
				m.Cliente_Mail,
				m.Cliente_Direccion,
				m.Cliente_Fecha_Nac,
				m.Cliente_Dni,
				m.Cliente_Dni
		FROM gd_esquema.Maestra m
		ORDER BY m.Cliente_Nombre
		

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CLIENTE')
GO



CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CHOFER
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.USUARIO (
		USUARIO_DNI,
		USUARIO_TEL,
		USUARIO_NOMBRE,
		USUARIO_APELLIDO,
		USUARIO_MAIL,
		USUARIO_DIR,
		USUARIO_FNAC,
		USUARIO_USERNAME,
		USUARIO_PASSWORD
	)	SELECT	distinct(m.Chofer_Dni),
				m.Chofer_Telefono,
				m.Chofer_Nombre,
				m.Chofer_Apellido,
				m.Chofer_Mail,
				m.Chofer_Direccion,
				m.Chofer_Fecha_Nac,
				m.Chofer_Dni,
				m.Chofer_Dni
		FROM gd_esquema.Maestra m

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_USUARIO_CHOFER')
GO



-----------------------------------------------------
----------------MIGRACION CLIENTE--------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_CLIENTE
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.CLIENTE (
		CLIENTE_ID
	) SELECT distinct(m.Cliente_Dni)
	  FROM gd_esquema.Maestra m

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_CLIENTE')
GO



-----------------------------------------------------
----------------MIGRACION CHOFER---------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_CHOFER
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.CHOFER(
		CHOFER_ID
	) SELECT distinct(m.Chofer_Dni)
	  FROM gd_esquema.Maestra m

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_CHOFER')
GO


----------------------------------------------------
----------MIGRACION ROL_X_USUARIO_CLIENTE-----------
----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CLIENTE
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.ROL_USUARIO (
		USROL_USUARIO,
		USROL_ROL
	)	SELECT	(c.CLIENTE_ID),
				2
		FROM DAVID_Y_LOS_COCODRILOS.CLIENTE c

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CLIENTE')
GO


----------------------------------------------------
-----------MIGRACION ROL_X_USUARIO_CHOFER------------
----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CHOFER
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.ROL_USUARIO (
		USROL_USUARIO,
		USROL_ROL
	)	SELECT	c.CHOFER_ID,
				3
		FROM DAVID_Y_LOS_COCODRILOS.CHOFER c

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_ROLxUSUARIO_CHOFER')
GO


-----------------------------------------------------
----------------MIGRACION MARCA----------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_MARCA
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.MARCA (
		MARCA_DETALLE
	)	SELECT distinct(m.Auto_Marca)
		FROM gd_esquema.Maestra m

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_MARCA')
GO

-----------------------------------------------------
----------------MIGRACION MODELO---------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_MODELO
AS 
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.MODELO (
		MODELO_MARCA, MODELO_DETALLE
	)	SELECT distinct (SELECT MARCA_ID FROM DAVID_Y_LOS_COCODRILOS.MARCA WHERE MARCA_DETALLE = m.Auto_Marca), m.Auto_Modelo 
		FROM gd_esquema.Maestra m

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_MODELO')
GO


-----------------------------------------------------
-----------------MIGRACION TURNOS--------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_TURNO 
AS 
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.TURNO (
		TURNO_HORA_INICIO,
		TURNO_HORA_FIN,
		TURNO_DESCRIPCION,
		TURNO_VALOR_KILOMETRO,
		TURNO_PRECIO_BASE,
		TURNO_HABILITADO
	)	(SELECT DISTINCT m.Turno_Hora_Inicio,
				m.Turno_Hora_Fin,
				m.Turno_Descripcion,
				m.Turno_Valor_Kilometro,
				m.Turno_Precio_Base,
				1
		FROM gd_esquema.Maestra m)
END		
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_TURNO')
GO

-----------------------------------------------------
----------------MIGRACION AUTOMOVIL------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_AUTOMOVIL 
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.AUTOMOVIL (
		AUTOMOVIL_PATENTE,
		AUTOMOVIL_MARCA,
		AUTOMOVIL_MODELO, 
		AUTOMOVIL_TURNO,
		AUTOMOVIL_CHOFER,
		AUTOMOVIL_HABILITADO
	)	SELECT	distinct(m.Auto_Patente), 
				(	SELECT marca.MARCA_ID
					FROM DAVID_Y_LOS_COCODRILOS.MARCA marca
					WHERE m.Auto_Marca = marca.MARCA_DETALLE 
				), 
				(	SELECT modelo.MODELO_ID
					FROM DAVID_Y_LOS_COCODRILOS.MODELO modelo
					WHERE m.Auto_Modelo = modelo.MODELO_DETALLE 
				),
				DAVID_Y_LOS_COCODRILOS.fGetTurno(m.Turno_Hora_Inicio, m.Turno_Hora_Fin),
				m.Chofer_Dni, 
				1
		FROM gd_esquema.Maestra m

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_AUTOMOVIL')
GO

-----------------------------------------------------
-------------MIGRACION TURNO AUTOMOVIL---------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_TURNO_AUTOMOVIL 
AS
BEGIN
	INSERT INTO DAVID_Y_LOS_COCODRILOS.TURNO_AUTOMOVIL (
		TA_AUTOMOVIL,
		TA_TURNO,
		TA_HABILITADO
	)SELECT DISTINCT Auto_Patente, DAVID_Y_LOS_COCODRILOS.fGetTurno(Turno_Hora_Inicio, Turno_Hora_Fin), 1 from gd_esquema.Maestra 
END
GO

-----------------------------------------------------
------------------MIGRACION VIAJE--------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.VIAJE (
		VIAJE_AUTOMOVIL_PATENTE,
		VIAJE_CHOFER,
		VIAJE_TURNO,
		VIAJE_CANTIDAD_KM,
		VIAJE_FECHA_INICIO,
		VIAJE_FECHA_FIN,
		VIAJE_CLIENTE
	)	SELECT	m.Auto_Patente,
				m.Chofer_Dni,
				(	SELECT t.TURNO_ID
					FROM DAVID_Y_LOS_COCODRILOS.TURNO t
					WHERE t.TURNO_HORA_INICIO = m.Turno_Hora_Inicio 
							and t.TURNO_HORA_FIN = m.Turno_Hora_Fin
				),
				max(m.Viaje_Cant_Kilometros),
				m.Viaje_Fecha,
				m.Viaje_Fecha, 
				m.Cliente_Dni
		FROM gd_esquema.Maestra m
		group by m.Chofer_Dni, m.Auto_Patente, m.Viaje_Fecha, m.Cliente_Dni, m.Turno_Hora_Inicio, m.Turno_Hora_Fin
END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE')
GO


---------------------------------------------------------------------
------------------MIGRACION VIAJE INCONSISTENCIAS--------------------
---------------------------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE_INCONSISTENCIAS
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.VIAJE_INCONSISTENCIAS (
		VIAJE_AUTOMOVIL_PATENTE,
		VIAJE_CHOFER,
		VIAJE_TURNO,
		VIAJE_CANTIDAD_KM,
		VIAJE_FECHA_INICIO,
		VIAJE_FECHA_FIN,
		VIAJE_CLIENTE
	)	SELECT	m.Auto_Patente,
				m.Chofer_Dni,
				(	SELECT t.TURNO_ID
					FROM DAVID_Y_LOS_COCODRILOS.TURNO t
					WHERE t.TURNO_HORA_INICIO = m.Turno_Hora_Inicio 
							and t.TURNO_HORA_FIN = m.Turno_Hora_Fin
				),
				MIN(m.Viaje_Cant_Kilometros),
				m.Viaje_Fecha,
				m.Viaje_Fecha, 
				m.Cliente_Dni
		FROM gd_esquema.Maestra m
		group by m.Chofer_Dni, m.Auto_Patente, m.Viaje_Fecha, m.Cliente_Dni, m.Turno_Hora_Inicio, m.Turno_Hora_Fin
		having count(*)>5
END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_VIAJE_INCONSISTENCIAS')
GO

-----------------------------------------------------
----------------MIGRACION PERIODO---------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_PERIODO
AS 
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.PERIODO (
		PERIODO_ANIO,
		PERIODO_MES,
		PERIODO_INICIO,
		PERIODO_FIN,
		PERIODO_CLIENTE
	)	(SELECT YEAR(Factura_Fecha_Inicio), MONTH(Factura_Fecha_Inicio), Factura_Fecha_Inicio, Factura_Fecha_Fin, Cliente_Dni
		from gd_esquema.Maestra 
		where Factura_Fecha_Inicio is not null and Factura_Fecha_Fin is not null
		group by Factura_Fecha_Inicio, Factura_Fecha_Fin, Cliente_Dni)
END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_PERIODO')
GO


-----------------------------------------------------
---------------------RENDICION-----------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_RENDICION 
AS
BEGIN
	INSERT INTO DAVID_Y_LOS_COCODRILOS.RENDICION (
		RENDICION_FECHA,
		RENDICION_CHOFER,
		RENDICION_TURNO
	)	SELECT	m.Rendicion_Fecha,
				m.Chofer_Dni,
				DAVID_Y_LOS_COCODRILOS.fGetTurno(m.Turno_Hora_Inicio, m.Turno_Hora_Fin)
		FROM gd_esquema.Maestra m
		WHERE Rendicion_Nro > 0 
		group by m.Rendicion_Fecha,m.Chofer_Dni,m.Turno_Hora_Inicio, m.Turno_Hora_Fin
END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_RENDICION')
GO



-----------------------------------------------------
----------------------FACTURA------------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_FACTURA 
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.FACTURA (
		FACTURA_CLIENTE,
		FACTURA_ANIO,
		FACTURA_PERIODO
	)	(SELECT	m.Cliente_Dni,
				YEAR(m.Factura_Fecha),
				MONTH(m.Factura_Fecha)

		FROM gd_esquema.Maestra m
		where m.Factura_Nro >0
		group by m.Cliente_Dni, m.Factura_Fecha
		)

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_FACTURA')
GO



-----------------------------------------------------
-----------------ITEM RENDICION----------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_RENDICION 
AS
BEGIN
	INSERT INTO DAVID_Y_LOS_COCODRILOS.ITEM_RENDICION (ITEMR_IMPORTE, ITEMR_CHOFER, ITEMR_CLIENTE, ITEMR_FECHA, ITEMR_TURNO, ITEMR_FECHA_VIAJE)
		(	SELECT	max(m.Rendicion_Importe), 
					m.Chofer_Dni,
					m.Cliente_Dni, 
					Rendicion_Fecha, 
					DAVID_Y_LOS_COCODRILOS.fGetTurno(m.Turno_Hora_Inicio, m.Turno_Hora_Fin), 
					Viaje_Fecha
			FROM gd_esquema.Maestra m
			WHERE Rendicion_Nro > 0
			group by m.Chofer_Dni, m.Cliente_Dni, Rendicion_Fecha, m.Turno_Hora_Inicio, m.Turno_Hora_Fin, Viaje_Fecha
		)
END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_RENDICION')
GO



-----------------------------------------------------
-----------------ITEM FACTURA------------------------
-----------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_FACTURA 
AS
BEGIN
	INSERT INTO DAVID_Y_LOS_COCODRILOS.ITEM_FACTURA (ITEMF_CHOFER, ITEMF_FECHA_VIAJE, ITEMF_CLIENTE, ITEMF_ANIO, ITEMF_PERIODO, ITEMF_IMPORTE)
	(
		SELECT	m.Chofer_Dni, 
				m.Viaje_Fecha, 
				m.Cliente_Dni,
				 YEAR(m.Factura_Fecha),
				  MONTH(m.Factura_Fecha), 
				  max(m.Turno_Precio_Base+(m.Turno_Valor_Kilometro*m.Viaje_Cant_Kilometros))
		FROM gd_esquema.Maestra m
		WHERE m.Factura_Nro>0
		group by m.Chofer_Dni, m.Viaje_Fecha, m.Cliente_Dni ,m.Factura_Fecha
	)

END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.MIGRACION_ITEM_FACTURA ')
GO

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.UPDATE_RENDICION 
AS
BEGIN
	UPDATE DAVID_Y_LOS_COCODRILOS.RENDICION SET RENDICION_IMPORTE = (SELECT COUNT(ITEMR_IMPORTE) FROM DAVID_Y_LOS_COCODRILOS.ITEM_RENDICION WHERE ITEMR_CHOFER = RENDICION_CHOFER AND ITEMR_FECHA = RENDICION_FECHA AND ITEMR_TURNO = RENDICION_TURNO)
END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.UPDATE_RENDICION')
GO


CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.UPDATE_FACTURA
AS
BEGIN
	UPDATE DAVID_Y_LOS_COCODRILOS.FACTURA SET FACTURA_IMPORTE = (SELECT COUNT(ITEMF_IMPORTE) FROM DAVID_Y_LOS_COCODRILOS.ITEM_FACTURA WHERE ITEMF_CLIENTE = FACTURA_CLIENTE AND ITEMF_ANIO = FACTURA_ANIO AND ITEMF_PERIODO = FACTURA_PERIODO)
END
GO

EXEC('DAVID_Y_LOS_COCODRILOS.UPDATE_FACTURA')
GO


--###########################################################################
--###########################################################################
------------------------------FUNCIONALIDADES--------------------------------
--###########################################################################
--###########################################################################



--DEVUELVE CANTIDAD DE INTENTOS DE LOGGIN FALLIDOS PARA UN USUARIO DADO
CREATE FUNCTION DAVID_Y_LOS_COCODRILOS.CANT_INTENTOS_LOGIN_FALLIDOS(@username char(35), @password char(100))
RETURNS int
AS
BEGIN

	RETURN (SELECT u.USUARIO_INTENTOS_LOGIN
			FROM DAVID_Y_LOS_COCODRILOS.USUARIO u
			WHERE u.USUARIO_USERNAME = @username AND
				  u.USUARIO_PASSWORD = @password
			)

END
GO 


---------------------------------------------------
-------------------LOGIN USUARIO-------------------
---------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.INGRESAR_USUARIO (
	@username char(35),
	@password char(100)
) 
AS
BEGIN

	DECLARE @status int = 999;
	DECLARE @userDNI numeric(18,0);

	IF EXISTS (	
		SELECT u.USUARIO_USERNAME
		FROM DAVID_Y_LOS_COCODRILOS.USUARIO u
		WHERE u.USUARIO_USERNAME = @username 
		) 

		BEGIN
			IF (SELECT u.USUARIO_PASSWORD
				FROM DAVID_Y_LOS_COCODRILOS.USUARIO u
				WHERE u.USUARIO_USERNAME = @username) = @password
					BEGIN
						IF( DAVID_Y_LOS_COCODRILOS.CANT_INTENTOS_LOGIN_FALLIDOS(@username, @password) < 3)
							BEGIN
								UPDATE DAVID_Y_LOS_COCODRILOS.USUARIO
								SET USUARIO_INTENTOS_LOGIN = 0
								WHERE USUARIO_USERNAME = @username

								SET @status = @@ERROR
							END
						ELSE
							BEGIN

								SET @userDNI = (SELECT u.USUARIO_DNI
											    FROM DAVID_Y_LOS_COCODRILOS.USUARIO u 
											    WHERE u.USUARIO_USERNAME = @username 
													  AND u.USUARIO_PASSWORD = @password
												)
								
								EXEC DAVID_Y_LOS_COCODRILOS.INHABILITAR_USUARIO @userDNI
								SET @status = 999
							END
					END;
			ELSE
				BEGIN
					UPDATE DAVID_Y_LOS_COCODRILOS.USUARIO 
					SET USUARIO_INTENTOS_LOGIN = USUARIO_INTENTOS_LOGIN + 1
					WHERE USUARIO_USERNAME = @username

					SET @status = 1001;
				END;
		END;
	ELSE
		SET @status = 999;

	IF(@status = 0)
		SELECT r.USROL_USUARIO, r.USROL_ROL, rol.ROL_DETALLE
		FROM DAVID_Y_LOS_COCODRILOS.ROL_USUARIO r JOIN DAVID_Y_LOS_COCODRILOS.ROL rol ON r.USROL_ROL = rol.ROL_ID
		WHERE r.USROL_USUARIO = (SELECT u.USUARIO_DNI
									FROM DAVID_Y_LOS_COCODRILOS.USUARIO u 
									WHERE u.USUARIO_USERNAME = @username
										  and r.USROL_HABILITADO = 1
									);
	ELSE
		SELECT @status;

END
GO


--------------------------------------------
--------OBTENER ROLES PARA UN USUARIO-------
--------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_PARA_USUARIO(@dni numeric(18,0))
AS
BEGIN

	SELECT r.USROL_ROL
	FROM DAVID_Y_LOS_COCODRILOS.ROL_USUARIO r
	WHERE r.USROL_USUARIO = @dni

END
GO



--------------------------------------------
-----OBTENER FUNCIONALIDADES PARA UN ROL----
--------------------------------------------

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONES_HABILITADAS_PARA_ROL(@rol int)
AS
BEGIN

--	IF( SELECT r.ROL_HABILITADO
--		FROM DAVID_Y_LOS_COCODRILOS.ROL r
--		WHERE r.ROL_ID = @rol ) = 1 

		SELECT f.FUNCIONALIDAD_ID, f.FUNCIONALIDAD_DETALLE
		FROM DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL r, DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD f
		WHERE r.ROLFUN_ROL = @rol 
			  and r.ROLFUN_FUNCIONALIDAD = f.FUNCIONALIDAD_ID
			  and f.FUNCIONALIDAD_HABILITADO = 1

--	ELSE
--		SELECT 1000; --error de rol no habilitado

END
GO


--------------------------------------------
-----OBTENER FUNCIONALIDADES PARA UN ROL----
--------------------------------------------

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TODAS_LAS_FUNCIONES_PARA_ROL(@rol int)
AS
BEGIN

--	IF( SELECT r.ROL_HABILITADO
--		FROM DAVID_Y_LOS_COCODRILOS.ROL r
--		WHERE r.ROL_ID = @rol ) = 1 

		SELECT f.FUNCIONALIDAD_ID, f.FUNCIONALIDAD_DETALLE
		FROM DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL fr 
				JOIN DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD f ON fr.ROLFUN_FUNCIONALIDAD = f.FUNCIONALIDAD_ID
		WHERE fr.ROLFUN_ROL = @rol

--	ELSE
--		SELECT 1000; --error de rol no habilitado

END
GO


--------------------------------------------
-----OBTENER TODOS LOS ROLES DEL SISTEMA----
--------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES 
AS
BEGIN

	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.ROL r

END
GO


--------------------------------------------------------------
--------------OBTENER TODOS LOS ROLES HABILITADOS-------------
--------------------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_ROLES_HABILITADOS(@detalle varchar(255))
AS 
BEGIN

	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.ROL r
	WHERE r.ROL_DETALLE = @detalle
		  and r.ROL_HABILITADO = 1

END
GO 


CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES_NO_ASIGNADAS_A_ROL(@rol int)
AS
BEGIN

	SELECT distinct(f.FUNCIONALIDAD_ID), f.FUNCIONALIDAD_DETALLE
		FROM DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL fr 
				JOIN DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD f ON fr.ROLFUN_FUNCIONALIDAD = f.FUNCIONALIDAD_ID
		WHERE  f.FUNCIONALIDAD_ID NOT IN (SELECT fr2.ROLFUN_FUNCIONALIDAD
									      FROM DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL fr2
										  WHERE fr2.ROLFUN_ROL = @rol )

END
GO


-------------------------------------------------------------
--OBTENER TODAS LAS FUNCIONALIDADES HABILITADAS DEL SISTEMA--
-------------------------------------------------------------

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FUNCIONALIDADES_HABILITADAS 
AS
BEGIN

	SELECT s.FUNCIONALIDAD_ID, s.FUNCIONALIDAD_DETALLE
	FROM DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD s
	WHERE s.FUNCIONALIDAD_HABILITADO = 1  --SOLO muestra los habilitados, esta bien?

END
GO

-------------------------------------------------
--OBTENER TODAS LAS FUNCIONALIDADES DEL SISTEMA--
-------------------------------------------------

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TODAS_LAS_FUNCIONALIDADES 
AS
BEGIN

	SELECT s.FUNCIONALIDAD_ID, s.FUNCIONALIDAD_DETALLE
	FROM DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD s

END
GO


--------------------------------------------------------
---------------OBTENER TODOS LOS ROLES------------------
--------------------------------------------------------

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TODOS_LOS_ROLES(@detalle varchar(255))
AS 
BEGIN

	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.ROL r
	WHERE r.ROL_DETALLE = @detalle

END
GO 




--###########################################################################
--###########################################################################
------------------------------INTERFAZ DE ABM--------------------------------
--###########################################################################
--###########################################################################

-------------------------------
-------ROL Y FUNCIONALIDAD-----
-------------------------------

--AGREGAR ROL
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.ALTA_ROL(@nombreRol varchar(255))
AS
BEGIN

	INSERT INTO DAVID_Y_LOS_COCODRILOS.ROL(
		ROL_DETALLE
	) VALUES (
		@nombreRol
	);

	IF @@ERROR <> 0
		RETURN 999
	ELSE 
		SELECT IDENT_CURRENT('DAVID_Y_LOS_COCODRILOS.ROL')

END
GO

--AGREGAR FUNCIONALIDAD A ROL
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_FUNCIONALIDAD_A_ROL(@rol int, @funcionalidad int)
AS
BEGIN

		INSERT INTO DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL(
			ROLFUN_ROL, 
			ROLFUN_FUNCIONALIDAD
		) 
		VALUES (
			@rol, 
			@funcionalidad
		)	

	SELECT @@ERROR

END
GO


--REMOVER FUNCIONALIDAD A ROL
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.REMOVER_FUNCIONALIDAD_A_ROL(@rol int, @funcionalidad int)
AS
BEGIN

	DELETE FROM DAVID_Y_LOS_COCODRILOS.FUNCIONALIDAD_ROL 
	WHERE ROLFUN_ROL = @rol AND
		  ROLFUN_FUNCIONALIDAD = @funcionalidad

	SELECT @@ERROR

END
GO 


--BAJA DE ROL
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_ROL(@rol int)
AS
BEGIN

	DECLARE @transaction varchar(30) = 'inhabilitarRol'
	DECLARE @result int = 0;

	BEGIN TRAN @transaction

		UPDATE DAVID_Y_LOS_COCODRILOS.ROL
		SET ROL_HABILITADO = 0
		WHERE ROL_ID = @rol

		UPDATE DAVID_Y_LOS_COCODRILOS.ROL_USUARIO
		SET USROL_HABILITADO = 0
		WHERE USROL_ROL = @rol
	 
/*		
		IF(@rol = 1)
			UPDATE DAVID_Y_LOS_COCODRILOS.ADMINISTRADOR
			SET ADMIN_HABILITADO = 0
		IF(@rol = 2)
			UPDATE DAVID_Y_LOS_COCODRILOS.CLIENTE 
			SET CLIENTE_HABILITADO = 0
		IF(@rol = 3)
			UPDATE DAVID_Y_LOS_COCODRILOS.CHOFER
			SET CHOFER_HABILITADO = 0 ;


			EN EL ENUNCIADO DICE QUE ELIMINA EL ROL DE LOS USUARIOS , SE ELIMINA CON DELETE O SE INHABILITA?
			*/

	COMMIT TRAN @transaction

	SET @result = @@ERROR
	
	IF @@ERROR <> 0 
		ROLLBACK TRAN @transaction;
			
	
	SELECT @result

END
GO 


--ALTA ROL
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.HABILITAR_ROL(@rol int)
AS
BEGIN

	UPDATE DAVID_Y_LOS_COCODRILOS.ROL
	SET ROL_HABILITADO = 1
	WHERE ROL_ID = @rol
	

	SELECT @@ERROR

END
GO 


--MODIFICACION NOMBRE DE ROL
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_NOMBRE_ROL(@rol int, @nuevoDetalle varchar(255))
AS
BEGIN

	UPDATE DAVID_Y_LOS_COCODRILOS.ROL
	SET ROL_DETALLE = @nuevoDetalle
	WHERE ROL_ID = @rol


	SELECT @@ERROR

END
GO 


-------------------------------------------------
------------USUARIO (CLIENTE Y CHOFER)-----------
-------------------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.ALTA_USUARIO(
	@rol int,
	@nombre varchar(255),
	@apellido varchar(255),
	@dni numeric(18,0),
	@mail varchar(50) = NULL,
	@telefono char(18),
	@direccion varchar(255),
	@piso int,
	@departamento char(10),
	@localidad varchar(50),
	@codPos varchar(10),
	@fechaNac datetime,
	@username char(35),
	@password char(10)
) 
AS
BEGIN

	DECLARE @transactionName varchar(30) = 'altaUsuario';

	BEGIN TRAN @transactionName
	BEGIN TRY
		IF( SELECT COUNT(*)
			FROM DAVID_Y_LOS_COCODRILOS.USUARIO u
			WHERE u.USUARIO_TEL = @telefono
		) = 0

			BEGIN
				INSERT INTO DAVID_Y_LOS_COCODRILOS.USUARIO (
					USUARIO_NOMBRE,
					USUARIO_APELLIDO,
					USUARIO_DNI,
					USUARIO_MAIL,
					USUARIO_TEL,
					USUARIO_DIR,
					USUARIO_PISO,
					USUARIO_DPTO,
					USUARIO_LOCALIDAD,
					USUARIO_CODPOS,
					USUARIO_FNAC,
					USUARIO_USERNAME,
					USUARIO_PASSWORD
				) VALUES (
					@nombre,
					@apellido,
					@dni,
					@mail,
					@telefono,
					@direccion,
					@piso,
					@departamento,
					@localidad,
					@codPos,
					@fechaNac,
					@username,
					@password
				)
			END

		IF(@rol = 1)
			INSERT INTO DAVID_Y_LOS_COCODRILOS.ADMINISTRADOR (
				ADMIN_ID
			) VALUES (
				@dni
			)
		IF(@rol = 2)
			INSERT INTO DAVID_Y_LOS_COCODRILOS.CLIENTE (
				CLIENTE_ID
			) VALUES (
				@dni
			)
		IF(@rol = 3) 
			INSERT INTO DAVID_Y_LOS_COCODRILOS.CHOFER (
				CHOFER_ID
			) VALUES (
				@dni
			)

		INSERT INTO DAVID_Y_LOS_COCODRILOS.ROL_USUARIO (
			USROL_USUARIO,
			USROL_ROL
		) VALUES (
			@dni,
			@rol
		)

		COMMIT TRAN @transactionName;
	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE()
		PRINT ERROR_NUMBER()
		ROLLBACK TRAN @transactionName;
		SELECT -1;
	END CATCH
		

END
GO 

--nombre, apellido, fechnac, telefono, direccion, piso, dpto, localidad, mail y habilitado
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_USUARIO(
	@dni numeric(18,0),
	@nombre varchar(255),
	@apellido varchar(255),
	@fechaNac datetime,
	@telefono char(18),
	@direccion varchar(255),
	@piso int,
	@departamento char(10),
	@localidad varchar(50),
	@mail varchar(50) = NULL,
	@habilitado bit,
	@codpos varchar(10)
) 
AS
BEGIN
	UPDATE DAVID_Y_LOS_COCODRILOS.USUARIO SET	USUARIO_NOMBRE = @nombre,
												USUARIO_APELLIDO = @apellido, 
												USUARIO_MAIL = @mail,
												USUARIO_TEL = @telefono,
												USUARIO_DIR = @direccion,
												USUARIO_PISO = @piso,
												USUARIO_DPTO = @departamento,
												USUARIO_LOCALIDAD = @localidad,
												USUARIO_CODPOS = @codPos,
												USUARIO_FNAC = @fechaNac
	WHERE USUARIO_DNI = @dni
END
GO

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_USUARIO(@dni numeric(18,0)) 
AS
BEGIN

	UPDATE DAVID_Y_LOS_COCODRILOS.USUARIO
	SET USUARIO_HABILITADO = 0
	WHERE USUARIO_DNI = @dni

	SELECT @@ERROR

END
GO


CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.BUSCAR_USUARIO(@nombre varchar(255), @apellido varchar(255), @dni numeric(18,0))
AS 
BEGIN

	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.USUARIO u
	WHERE	(@nombre is null or @nombre = u.USUARIO_NOMBRE) and
			(@apellido is null or @apellido = u.USUARIO_APELLIDO) and
			(@dni is null or @dni = u.USUARIO_DNI)

END
GO




---------------------------------------
-----OBTENER FECHA INICIO PERIODO------
---------------------------------------
CREATE FUNCTION DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_INICIO_PERIODO
(@ANIO INT, @PERIODO INT, @CLIENTE NUMERIC(18,0))
RETURNS DATETIME
AS
BEGIN
	RETURN (SELECT PERIODO_INICIO FROM DAVID_Y_LOS_COCODRILOS.PERIODO WHERE PERIODO_ANIO = @ANIO AND PERIODO_MES = @PERIODO AND PERIODO_CLIENTE = @CLIENTE)
END
GO


---------------------------------------
-------OBTENER FECHA FIN PERIODO-------
---------------------------------------
CREATE FUNCTION DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_FIN_PERIODO
(@ANIO INT, @PERIODO INT, @CLIENTE NUMERIC(18,0))
RETURNS DATETIME
AS
BEGIN
	RETURN (SELECT PERIODO_FIN FROM DAVID_Y_LOS_COCODRILOS.PERIODO WHERE PERIODO_ANIO = @ANIO AND PERIODO_MES = @PERIODO AND PERIODO_CLIENTE = @CLIENTE)
END
GO


---------------------------------------
----------- AGREGAR AUTOMOVIL----------
---------------------------------------

CREATE TYPE DAVID_Y_LOS_COCODRILOS.T_TURNOS
AS TABLE
(
  CAMPO_TURNO INT
);
GO

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_AUTOMOVIL
(@PATENTE VARCHAR(10),@MARCA INT, @MODELO INT, @TURNO AS DAVID_Y_LOS_COCODRILOS.T_TURNOS READONLY , @CHOFER NUMERIC(18,0))
AS
BEGIN
	DECLARE @RESULTADO INT;

	SELECT @RESULTADO = (SELECT COUNT(*) FROM DAVID_Y_LOS_COCODRILOS.AUTOMOVIL WHERE AUTOMOVIL_CHOFER = @CHOFER AND AUTOMOVIL_HABILITADO = 1)
	IF (@RESULTADO = 0)
	BEGIN

		SELECT @RESULTADO = (SELECT COUNT(*) FROM DAVID_Y_LOS_COCODRILOS.AUTOMOVIL WHERE AUTOMOVIL_PATENTE = @PATENTE)
		IF (@RESULTADO = 0)
		BEGIN
			INSERT INTO DAVID_Y_LOS_COCODRILOS.AUTOMOVIL (AUTOMOVIL_PATENTE, AUTOMOVIL_MARCA, AUTOMOVIL_MODELO, AUTOMOVIL_TURNO, AUTOMOVIL_CHOFER, AUTOMOVIL_HABILITADO) 
														(SELECT @PATENTE, @MARCA, @MODELO, t.CAMPO_TURNO, @CHOFER, 1 FROM @TURNO t)
		END

	END

	SELECT @RESULTADO
END
GO


---------------------------------------
--------- OBTENER_AUTOMOVILES----------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVILES
(@PATENTE VARCHAR(10) ,@MARCA varchar(255), @MODELO varchar(255),  @CHOFER NUMERIC(18,0))
AS
BEGIN
	SELECT AUTOMOVIL_PATENTE, AUTOMOVIL_CHOFER, MARCA_DETALLE, MODELO_DETALLE, AUTOMOVIL_TURNO, AUTOMOVIL_HABILITADO
	FROM DAVID_Y_LOS_COCODRILOS.AUTOMOVIL JOIN DAVID_Y_LOS_COCODRILOS.MARCA ON MARCA_ID = AUTOMOVIL_MARCA JOIN DAVID_Y_LOS_COCODRILOS.MODELO ON MODELO_ID = AUTOMOVIL_MODELO
	WHERE (@PATENTE IS NULL OR AUTOMOVIL_PATENTE = @PATENTE)
	AND (@MARCA IS NULL OR @MARCA = ' ' OR MARCA_DETALLE = @MARCA)
	AND (@MODELO IS NULL OR @MODELO = ' ' OR MODELO_DETALLE = @MODELO)
	AND (@CHOFER IS NULL OR @CHOFER = 0 OR AUTOMOVIL_CHOFER = @CHOFER)
END
GO

---------------------------------------
----------- OBTENER_AUTOMOVILES_HABILITADOS----------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_AUTOMOVILES_HABILITADOS
(@PATENTE VARCHAR(10) ,@MARCA varchar(255), @MODELO varchar(255),  @CHOFER NUMERIC(18,0))
AS
BEGIN
	SELECT AUTOMOVIL_PATENTE, AUTOMOVIL_CHOFER, MARCA_DETALLE, MODELO_DETALLE, AUTOMOVIL_TURNO 
	FROM DAVID_Y_LOS_COCODRILOS.AUTOMOVIL JOIN DAVID_Y_LOS_COCODRILOS.MARCA ON MARCA_ID = AUTOMOVIL_MARCA JOIN DAVID_Y_LOS_COCODRILOS.MODELO ON MODELO_ID = AUTOMOVIL_MODELO
	WHERE (@PATENTE IS NULL OR AUTOMOVIL_PATENTE = @PATENTE)
	AND (@MARCA IS NULL OR @MARCA = ' ' OR MARCA_DETALLE = @MARCA)
	AND (@MODELO IS NULL OR @MODELO = ' ' OR MODELO_DETALLE = @MODELO)
	AND (@CHOFER IS NULL OR @CHOFER = 0 OR AUTOMOVIL_CHOFER = @CHOFER)
	AND AUTOMOVIL_HABILITADO = 1
END
GO

---------------------------------------
--------INHABILITAAR AUTOMOVIL---------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_AUTOMOVIL
(@PATENTE VARCHAR(10), @TURNO INT)
AS
BEGIN
	UPDATE DAVID_Y_LOS_COCODRILOS.AUTOMOVIL SET AUTOMOVIL_HABILITADO = 0 WHERE AUTOMOVIL_PATENTE = @PATENTE AND (@TURNO IS NULL OR AUTOMOVIL_TURNO = @TURNO)
END
GO

---------------------------------------
--------MODIFICAR AUTOMOVIL---------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_AUTOMOVIL
(@PATENTE VARCHAR(10), @MARCA varchar(255), @MODELO varchar(255),  @CHOFER NUMERIC(18,0), @HABILITADO BIT)
AS
BEGIN
	DECLARE @RESULTADO INT;
	SELECT @RESULTADO = (SELECT COUNT(*) FROM DAVID_Y_LOS_COCODRILOS.AUTOMOVIL WHERE AUTOMOVIL_CHOFER = @CHOFER AND AUTOMOVIL_HABILITADO = 1 AND AUTOMOVIL_PATENTE <> @PATENTE)
	IF (@RESULTADO = 0)
	BEGIN
		UPDATE DAVID_Y_LOS_COCODRILOS.AUTOMOVIL 
		SET AUTOMOVIL_MARCA = (SELECT MARCA_ID FROM DAVID_Y_LOS_COCODRILOS.MARCA WHERE MARCA_DETALLE = @MARCA),
		AUTOMOVIL_MODELO = (SELECT MODELO_ID FROM DAVID_Y_LOS_COCODRILOS.MODELO WHERE MODELO_DETALLE = @MODELO),
		AUTOMOVIL_CHOFER = @CHOFER,
		AUTOMOVIL_HABILITADO = @HABILITADO
		WHERE AUTOMOVIL_PATENTE = @PATENTE
	END
	SELECT @RESULTADO
END
GO


---------------------------------------
------------OBTENER MARCAS-------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_MARCAS
AS
BEGIN
	
	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.MARCA

END
GO


---------------------------------------
------------OBTENER MODELOS------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_MODELOS
AS
BEGIN
	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.MODELO
END
GO


---------------------------------------
------OBTENER TURNOS HABILITADOS-------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TURNOS_HABILITADOS
AS
BEGIN

	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.TURNO t
	WHERE t.TURNO_HABILITADO = 1

END
GO

---------------------------------------
------------OBTENER TURNOS-------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_TURNOS
AS
BEGIN

	SELECT *
	FROM DAVID_Y_LOS_COCODRILOS.TURNO t

END
GO

---------------------------------------
----------INHABILITAR TURNOS-----------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.INHABILITAR_TURNO
(@ID INT)
AS
BEGIN

	UPDATE DAVID_Y_LOS_COCODRILOS.TURNO SET TURNO_HABILITADO = 0 WHERE TURNO_ID = @ID 

END
GO

---------------------------------------
------------MODIFICAR TURNO------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.MODIFICAR_TURNO
(@ID INT, @HORA_INICIO NUMERIC(18,0), @HORA_FIN NUMERIC(18,0), @DESCRIPCION VARCHAR(255), @VALOR_KILOMETRO NUMERIC(18,2), @PRECIO_BASE NUMERIC(18,2), @HABILITADO BIT)
AS
BEGIN
	DECLARE @RESULTADO INT;

	IF (@HABILITADO = 1)
		BEGIN
			SELECT @RESULTADO  = (SELECT COUNT(*)
								FROM DAVID_Y_LOS_COCODRILOS.TURNO
								WHERE (	TURNO_HABILITADO = 1 
											AND (	@HORA_INICIO BETWEEN TURNO_HORA_INICIO AND TURNO_HORA_FIN 
											OR @HORA_FIN BETWEEN TURNO_HORA_INICIO AND TURNO_HORA_FIN 
											OR TURNO_HORA_INICIO BETWEEN @HORA_INICIO AND @HORA_FIN) )
										OR @HORA_INICIO = TURNO_HORA_INICIO AND @HORA_FIN = TURNO_HORA_FIN)
			IF (@RESULTADO = 0)
			BEGIN
				UPDATE DAVID_Y_LOS_COCODRILOS.TURNO SET TURNO_HORA_INICIO = @HORA_INICIO, TURNO_HORA_FIN = @HORA_FIN, TURNO_DESCRIPCION = @DESCRIPCION, TURNO_VALOR_KILOMETRO = @VALOR_KILOMETRO, TURNO_PRECIO_BASE = @PRECIO_BASE, TURNO_HABILITADO = @HABILITADO WHERE TURNO_ID = @ID
			END
		END
	ELSE
	BEGIN
		UPDATE DAVID_Y_LOS_COCODRILOS.TURNO SET TURNO_HORA_INICIO = @HORA_INICIO, TURNO_HORA_FIN = @HORA_FIN, TURNO_DESCRIPCION = @DESCRIPCION, TURNO_VALOR_KILOMETRO = @VALOR_KILOMETRO, TURNO_PRECIO_BASE = @PRECIO_BASE, TURNO_HABILITADO = @HABILITADO WHERE TURNO_ID = @ID
	END

	SELECT *  FROM DAVID_Y_LOS_COCODRILOS.TURNO WHERE  TURNO_ID = @ID 
END
GO

---------------------------------------
-------------AGREGAR TURNO------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_TURNO
(@HORA_INICIO NUMERIC(18,0), @HORA_FIN NUMERIC(18,0), @DESCRIPCION VARCHAR(255), @VALOR_KILOMETRO NUMERIC(18,2), @PRECIO_BASE NUMERIC(18,2))
AS
BEGIN
	DECLARE @RESULTADO INT;

	SELECT @RESULTADO  = (SELECT COUNT(*)
						FROM DAVID_Y_LOS_COCODRILOS.TURNO
						WHERE (	TURNO_HABILITADO = 1 
									AND (	@HORA_INICIO BETWEEN TURNO_HORA_INICIO AND TURNO_HORA_FIN 
									OR @HORA_FIN BETWEEN TURNO_HORA_INICIO AND TURNO_HORA_FIN 
									OR TURNO_HORA_INICIO BETWEEN @HORA_INICIO AND @HORA_FIN) )
								OR @HORA_INICIO = TURNO_HORA_INICIO AND @HORA_FIN = TURNO_HORA_FIN)

	IF (@RESULTADO = 0)
	BEGIN
		INSERT INTO DAVID_Y_LOS_COCODRILOS.TURNO 
			(TURNO_HORA_INICIO, TURNO_HORA_FIN, TURNO_DESCRIPCION, TURNO_VALOR_KILOMETRO, TURNO_PRECIO_BASE, TURNO_HABILITADO)
		VALUES (@HORA_INICIO, @HORA_FIN, @DESCRIPCION, @VALOR_KILOMETRO, @PRECIO_BASE, 1)
	END

	SELECT @RESULTADO
END
GO



---------------------------------------
-------------AGREGAR VIAJE-------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.AGREGAR_VIAJE
(@CHOFER NUMERIC(18,0), @CLIENTE NUMERIC(18,0), @AUTOMOVIL VARCHAR(10), @TURNO CHAR(1), @CANTIDAD_KM NUMERIC(18,0), @FECHA_INICIO DATETIME, @FECHA_FIN DATETIME)
AS
BEGIN
INSERT INTO DAVID_Y_LOS_COCODRILOS.VIAJE (VIAJE_CHOFER, VIAJE_CLIENTE, VIAJE_AUTOMOVIL_PATENTE, VIAJE_TURNO, VIAJE_CANTIDAD_KM, VIAJE_FECHA_INICIO, VIAJE_FECHA_FIN)  VALUES 
			(@CHOFER, @CLIENTE, @AUTOMOVIL, @TURNO, @CANTIDAD_KM, @FECHA_INICIO, @FECHA_FIN)
END
GO

---------------------------------------
-------------OBTENER VIAJES------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_VIAJE
(@CHOFER NUMERIC(18,0), @CLIENTE NUMERIC(18,0), @AUTOMOVIL VARCHAR(10), @TURNO CHAR(1), @FECHA_INICIO DATETIME, @FECHA_FIN DATETIME)
AS
BEGIN
    SELECT * 
	FROM DAVID_Y_LOS_COCODRILOS.VIAJE
	WHERE (@CHOFER IS NULL OR VIAJE_CHOFER = @CHOFER)
	AND (@CLIENTE IS NULL OR VIAJE_CLIENTE = @CLIENTE)
	AND (@AUTOMOVIL IS NULL OR VIAJE_AUTOMOVIL_PATENTE = @AUTOMOVIL)
	AND (@TURNO IS NULL OR VIAJE_TURNO = @TURNO)
	AND	(@FECHA_INICIO IS NULL OR VIAJE_FECHA_INICIO = @FECHA_INICIO)
	AND	(@FECHA_FIN IS NULL OR VIAJE_FECHA_FIN = @FECHA_FIN)
END
GO

---------------------------------------
----------------RENDIR-----------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.RENDIR
(@FECHA DATE, @CHOFER NUMERIC(18,0), @TURNO CHAR(1))
AS
BEGIN
	BEGIN TRANSACTION

	BEGIN TRY
		INSERT INTO DAVID_Y_LOS_COCODRILOS.RENDICION (RENDICION_FECHA, RENDICION_CHOFER, RENDICION_TURNO) VALUES (@FECHA, @CHOFER, @TURNO)

		INSERT INTO DAVID_Y_LOS_COCODRILOS.ITEM_RENDICION 
			SELECT (TURNO_PRECIO_BASE+(VIAJE_CANTIDAD_KM*TURNO_VALOR_KILOMETRO)), VIAJE_CHOFER, VIAJE_CLIENTE, @FECHA, VIAJE_TURNO,VIAJE_FECHA_INICIO  
			FROM DAVID_Y_LOS_COCODRILOS.VIAJE JOIN DAVID_Y_LOS_COCODRILOS.TURNO ON VIAJE_TURNO = TURNO_ID
			WHERE VIAJE_FECHA_INICIO BETWEEN @FECHA AND DATEADD(DAY, 1, @FECHA);
	
		UPDATE DAVID_Y_LOS_COCODRILOS.RENDICION 
		SET RENDICION_IMPORTE =		(SELECT COUNT(ITEMR_IMPORTE) 
									FROM DAVID_Y_LOS_COCODRILOS.ITEM_RENDICION 
									WHERE ITEMR_CHOFER = @CHOFER AND ITEMR_FECHA = @FECHA AND ITEMR_TURNO = @TURNO)
		WHERE RENDICION_CHOFER = @CHOFER AND RENDICION_FECHA = @FECHA AND RENDICION_TURNO = @TURNO				
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
	END CATCH
END
GO

---------------------------------------
---------OBTENER RENDICIONES-----------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_RENDICIONES
(@FECHA DATE, @CHOFER NUMERIC(18,0), @TURNO CHAR(1))
AS
BEGIN
	SELECT * FROM DAVID_Y_LOS_COCODRILOS.RENDICION 
	WHERE (@FECHA IS NULL OR RENDICION_FECHA = @FECHA)
	AND (@CHOFER IS NULL OR RENDICION_CHOFER = @CHOFER)
	AND (@TURNO IS NULL OR RENDICION_TURNO = @TURNO)
END
GO

---------------------------------------
---------------FACTURAR----------------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.FACTURAR
(@CLIENTE NUMERIC(18,0), @FECHA DATE)
AS
BEGIN
	BEGIN TRANSACTION

		BEGIN TRY
			INSERT INTO DAVID_Y_LOS_COCODRILOS.FACTURA (FACTURA_CLIENTE, FACTURA_ANIO, FACTURA_PERIODO) VALUES (@CLIENTE, YEAR(@FECHA), MONTH(@FECHA))

			INSERT INTO DAVID_Y_LOS_COCODRILOS.ITEM_FACTURA
				SELECT VIAJE_CHOFER,VIAJE_FECHA_INICIO, VIAJE_CLIENTE, YEAR(@FECHA), MONTH(@FECHA), (TURNO_PRECIO_BASE+(VIAJE_CANTIDAD_KM*TURNO_VALOR_KILOMETRO))
				FROM DAVID_Y_LOS_COCODRILOS.VIAJE JOIN DAVID_Y_LOS_COCODRILOS.TURNO ON VIAJE_TURNO = TURNO_ID
				WHERE VIAJE_CLIENTE = @CLIENTE 
				AND VIAJE_FECHA_INICIO > DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_INICIO_PERIODO(YEAR(@FECHA), MONTH(@FECHA), @CLIENTE) 
				AND VIAJE_FECHA_FIN < DAVID_Y_LOS_COCODRILOS.OBTENER_FECHA_FIN_PERIODO(YEAR(@FECHA), MONTH(@FECHA), @CLIENTE) 

			UPDATE DAVID_Y_LOS_COCODRILOS.FACTURA 
			SET FACTURA_IMPORTE =	(SELECT COUNT(ITEMF_IMPORTE)
											FROM DAVID_Y_LOS_COCODRILOS.ITEM_FACTURA
											WHERE ITEMF_CLIENTE = @CLIENTE AND ITEMF_ANIO = YEAR(@FECHA) AND ITEMF_PERIODO = MONTH(@FECHA))
			WHERE FACTURA_CLIENTE = @CLIENTE AND FACTURA_ANIO = YEAR(@FECHA) AND FACTURA_PERIODO = MONTH(@FECHA)

			COMMIT TRANSACTION
		END TRY
		BEGIN CATCH
			ROLLBACK TRANSACTION
		END CATCH
END
GO

---------------------------------------
---------OBTENER RENDICIONES-----------
---------------------------------------
CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.OBTENER_FACTURAS
(@FECHA DATE, @CLIENTE NUMERIC(18,0))
AS
BEGIN
	SELECT * FROM DAVID_Y_LOS_COCODRILOS.FACTURA
	WHERE (@FECHA IS NULL OR (FACTURA_ANIO = YEAR(@FECHA) AND FACTURA_PERIODO = MONTH(@FECHA)))
	AND (@CLIENTE IS NULL OR FACTURA_CLIENTE = @CLIENTE)

END
GO

-- ESTADISTICAS 

-- CHOFERES CON MAYOR RECAUDACION

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_RECAUDACION
(@ANIO INT, @MES_INICIO INT, @MES_FIN INT)
AS
	SELECT TOP 5 SUM(RENDICION_IMPORTE) AS IMPORTE_TOTAL, USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_DNI, USUARIO_LOCALIDAD, USUARIO_DIR
	FROM DAVID_Y_LOS_COCODRILOS.USUARIO JOIN DAVID_Y_LOS_COCODRILOS.RENDICION ON USUARIO_DNI = RENDICION_CHOFER
	WHERE MONTH(RENDICION_FECHA) BETWEEN @MES_INICIO AND @MES_FIN AND YEAR(RENDICION_FECHA) = @ANIO
	GROUP BY USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_DNI, USUARIO_LOCALIDAD, USUARIO_DIR
	ORDER BY IMPORTE_TOTAL DESC
GO

-- CHOFERES CON EL VIAJE MAS LARGO REGISTRADO

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_VIAJES_MAS_LARGOS
(@ANIO INT, @MES_INICIO INT, @MES_FIN INT)
AS
	SELECT TOP 5 VIAJE_ID, VIAJE_FECHA_INICIO, VIAJE_CANTIDAD_KM, USUARIO_DNI, USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_LOCALIDAD, USUARIO_DIR
	FROM DAVID_Y_LOS_COCODRILOS.USUARIO JOIN DAVID_Y_LOS_COCODRILOS.VIAJE ON USUARIO_DNI = VIAJE_CHOFER
	WHERE MONTH(VIAJE_FECHA_INICIO) BETWEEN @MES_INICIO AND @MES_FIN AND YEAR(VIAJE_FECHA_INICIO) = @ANIO
	ORDER BY VIAJE_CANTIDAD_KM DESC
GO

-- CLIENTES CON MAYOR CONSUMO

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_CLIENTES_CONSUMO
(@ANIO INT, @MES_INICIO INT, @MES_FIN INT)
AS
	SELECT TOP 5 SUM(FACTURA_IMPORTE) AS IMPORTE_TOTAL, USUARIO_DNI, USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_LOCALIDAD, USUARIO_DIR
	FROM DAVID_Y_LOS_COCODRILOS.USUARIO JOIN DAVID_Y_LOS_COCODRILOS.FACTURA ON USUARIO_DNI = FACTURA_CLIENTE
	WHERE FACTURA_ANIO = @ANIO AND FACTURA_PERIODO BETWEEN @MES_INICIO AND @MES_FIN
	GROUP BY USUARIO_DNI, USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_LOCALIDAD, USUARIO_DIR
	ORDER BY IMPORTE_TOTAL
GO

-- CLIENTE QUE USO MAS VECES EL MISMO AUTOMOVIL

CREATE PROCEDURE DAVID_Y_LOS_COCODRILOS.ESTADISTICA_CLIENTE_AUTOMOVIL
(@ANIO INT, @MES_INICIO INT, @MES_FIN INT)
AS
	SELECT TOP 5 COUNT(VIAJE_AUTOMOVIL_PATENTE) AS CANTIDAD_USOS, AUTOMOVIL_PATENTE, AUTOMOVIL_MARCA, AUTOMOVIL_MODELO, USUARIO_DNI, USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_LOCALIDAD, USUARIO_DIR
	FROM VIAJE JOIN AUTOMOVIL ON VIAJE_AUTOMOVIL_PATENTE = AUTOMOVIL_PATENTE JOIN USUARIO ON VIAJE_CLIENTE = USUARIO_DNI
	WHERE MONTH(VIAJE_FECHA_INICIO) BETWEEN @MES_INICIO AND @MES_FIN AND YEAR(VIAJE_FECHA_INICIO) = @ANIO
	GROUP BY AUTOMOVIL_PATENTE, AUTOMOVIL_MARCA, AUTOMOVIL_MODELO, USUARIO_DNI, USUARIO_NOMBRE, USUARIO_APELLIDO, USUARIO_LOCALIDAD, USUARIO_DIR
	ORDER BY CANTIDAD_USOS DESC

GO


